#!/bin/bash
mace_run_train \
    --name="MACE_BTO" \
    --train_file="../../train.xyz" \
    --valid_fraction=0.05 \
    --energy_key="energy" \
    --forces_key="forces" \
    --E0s='average' \
    --model="MACELES" \
    --hidden_irreps='128x0e + 128x1o' \
    --r_max=6 \
    --num_interactions=2 \
    --batch_size=10 \
    --max_num_epochs=1000 \
    --stage_two \
    --start_stage_two=500 \
    --ema \
    --ema_decay=0.99 \
    --amsgrad \
    --restart_latest \
    --device=cuda \
    --save_cpu \
    --patience=20 \
