name: compile pdf

on:
  push:
    branches:
      - 'release/*'
      - 'master'
      - 'main'
      - 'revise'
      - 'develop'
      - 'feature/*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile all
        uses: docker://ghcr.io/kiyou/latex:latest
        with:
          entrypoint: 'make'
